const express = require("express")
const { registername, loginuser, logout, frogotpassword, resetpassword, updateprofile, getalluser, getsingleuser, getuserdetails, updatepassword, loginUser, updaterol, deleteuser, updateUserRole } = require("../controllers/usercontroller")
const { isauthenticateduser, authorizeroles } = require("../middelware/auth")
const router =express.Router()
router.route("/register").post(registername)
router.route("/login").post(loginUser)
router.route("/logout").get(logout)
router.route("/password/forgot").post(frogotpassword)
router.route("/password/reset/:token").put(resetpassword)
router.route("/password/update").put(isauthenticateduser,updatepassword)
router.route("/me").get(isauthenticateduser,getuserdetails)
router.route("/me/update").put(isauthenticateduser,updateprofile)
router.route("/admin/users").get(isauthenticateduser,getalluser)
router.route("/admin/users/:id").get(isauthenticateduser,getsingleuser).put(isauthenticateduser,authorizeroles("admin"),updateUserRole).delete(isauthenticateduser,authorizeroles("admin"),deleteuser)
module.exports =router